apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  username: a2lhbGl1c2Vy
  passphrase: a2lhbGlwYXNzd29yZA==

# username: kialiuser
# password: kialipassword