apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: customermanagementapi-mirror
  namespace: pitstop
spec:
  host: customermanagementapi
  subsets:
    - name: version-v1
      labels:
        version: v1
    - name: version-v2
      labels:
        version: v2

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customermanagementapi-mirror
  namespace: pitstop
spec:
  hosts:
    - customermanagementapi
  http:
    - route:
      - destination:
          host: customermanagementapi
          subset: version-v1
        weight: 100
      mirror:
        host: customermanagementapi
        subset: version-v2
